export default {
  ['Adlm']: 'Adlam',
  ['Afak']: 'Afaka',
  ['Aghb']: 'Caucasian Albanian',
  ['Ahom']: 'Ahom',
  ['Arab']: 'Arabic',
  ['Armi']: 'Imperial Aramaic',
  ['Armn']: 'Armenian',
  ['Avst']: 'Avestan',
  ['Bali']: 'Balinese',
  ['Bamu']: 'Bamum',
  ['Bass']: 'Bassa',
  ['Batk']: 'Batak',
  ['Beng']: 'Bengali',
  ['Bhks']: 'Bhaiksuki',
  ['Blis']: 'Blissymbols',
  ['Bopo']: 'Zhuyin',
  ['Brah']: 'Brahmi',
  ['Brai']: 'Braille',
  ['Bugi']: 'Buginese',
  ['Buhd']: 'Buhid',
  ['Cakm']: 'Chakma',
  ['Cans']: 'Canadian syllabics',
  ['Cari']: 'Carian',
  ['Cham']: 'Cham',
  ['Cher']: 'Cherokee',
  ['Chrs']: 'Chorasmian',
  ['Copt']: 'Coptic',
  ['Cpmn']: 'Cypro-Minoan',
  ['Cprt']: 'Cypriot',
  ['Cyrl']: 'Cyrillic',
  ['Cyrs']: 'Old Cyrillic',
  ['Deva']: 'Devanagari',
  ['Diak']: 'Dhives Akuru',
  ['Dogr']: 'Dogra',
  ['Dsrt']: 'Deseret',
  ['Dupl']: 'Duployan',
  ['Egyd']: 'Demotic',
  ['Egyh']: 'Hieratic',
  ['Egyp']: 'Egyptian hieroglyphic',
  ['Elba']: 'Elbasan',
  ['Elym']: 'Elymaic',
  ['Ethi']: 'Ethiopic',
  ['Geok']: 'Khutsuri',
  ['Geor']: 'Georgian',
  ['Glag']: 'Glagolitic',
  ['Gong']: 'Gunjala Gondi',
  ['Gonm']: 'Masaram Gondi',
  ['Goth']: 'Gothic',
  ['Gran']: 'Grantha',
  ['Grek']: 'Greek',
  ['Gujr']: 'Gujarati',
  ['Guru']: 'Gurmukhi',
  ['Hang']: 'Hangul',
  ['Hani']: 'Han',
  ['Hano']: 'Hanunoo',
  ['Hans']: 'Simplified Han',
  ['Hant']: 'Traditional Han',
  ['Hatr']: 'Hatran',
  ['Hebr']: 'Hebrew',
  ['Hira']: 'Hiragana',
  ['Hluw']: 'Anatolian Hieroglyphs',
  ['Hmng']: 'Pahawh Hmong',
  ['Hmnp']: 'Nyiakeng Puachue Hmong',
  ['Hung']: 'Old Hungarian',
  ['Ipach']: 'International Phonetic Alphabet',
  ['IPAchar']: 'International Phonetic Alphabet',
  ['Ibrn']: 'Iberian',
  ['Imag']: 'Image-rendered',
  ['Inds']: 'Indus',
  ['Ital']: 'Old Italic',
  ['Java']: 'Javanese',
  ['Jpan']: 'Japanese',
  ['Jurc']: 'Jurchen',
  ['Kali']: 'Kayah Li',
  ['Kana']: 'Katakana',
  ['Kawi']: 'Kawi',
  ['Khar']: 'Kharoshthi',
  ['Khmr']: 'Khmer',
  ['Khoj']: 'Khojki',
  ['Kitl']: 'Khitan Large',
  ['Kits']: 'Khitan Small',
  ['Knda']: 'Kannada',
  ['Kore']: 'Korean',
  ['Kpel']: 'Kpelle',
  ['Kthi']: 'Kaithi',
  ['Lana']: 'Tai Tham',
  ['Laoo']: 'Lao',
  ['Latf']: 'Fraktur',
  ['Latg']: 'Gaelic',
  ['Latinx']: 'Latin',
  ['Latn']: 'Latin',
  ['Latnx']: 'Latin',
  ['Leke']: 'Leke',
  ['Lepc']: 'Lepcha',
  ['Limb']: 'Limbu',
  ['Lina']: 'Linear A',
  ['Linb']: 'Linear B',
  ['Lisu']: 'Lisu',
  ['Loma']: 'Loma',
  ['Lyci']: 'Lycian',
  ['Lydi']: 'Lydian',
  ['Mahj']: 'Mahajani',
  ['Maka']: 'Lontara',
  ['Mand']: 'Mandaic',
  ['Mani']: 'Manichaean',
  ['Marc']: 'Marchen',
  ['Maya']: 'Maya',
  ['Medf']: 'Medefaidrin',
  ['Mend']: 'Mende',
  ['Merc']: 'Meroitic cursive',
  ['Mero']: 'Meroitic hieroglyphic',
  ['Mlym']: 'Malayalam',
  ['Modi']: 'Modi',
  ['Mong']: 'Mongolian',
  ['Moon']: 'Moon',
  ['Morse']: 'Morse code',
  ['Mroo']: 'Mro',
  ['Mtei']: 'Meitei Mayek',
  ['Mult']: 'Multani',
  ['Music']: 'Musical notation',
  ['Mymr']: 'Burmese',
  ['Nagm']: 'Nag Mundari',
  ['Nand']: 'Nandinagari',
  ['Narb']: 'Old North Arabian',
  ['Nbat']: 'Nabataean',
  ['Newa']: 'Newa',
  ['Nkdb']: 'Dongba',
  ['Nkgb']: 'Geba',
  ['Nkoo']: "N'Ko",
  ['None']: 'Unspecified',
  ['Nshu']: 'Nüshu',
  ['Ogam']: 'Ogham',
  ['Olck']: 'Ol Chiki',
  ['Orkh']: 'Orkhon runes',
  ['Orya']: 'Oriya',
  ['Osge']: 'Osage',
  ['Osma']: 'Osmanya',
  ['Ougr']: 'Old Uyghur',
  ['Palm']: 'Palmyrene',
  ['Pauc']: 'Pau Cin Hau',
  ['Perm']: 'Old Permic',
  ['Phag']: 'Phags-pa',
  ['Phli']: 'Inscriptional Pahlavi',
  ['Phlp']: 'Psalter Pahlavi',
  ['Phlv']: 'Book Pahlavi',
  ['Phnx']: 'Phoenician',
  ['Plrd']: 'Pollard',
  ['Polyt']: 'Greek',
  ['Prti']: 'Inscriptional Parthian',
  ['Ranj']: 'Ranjana',
  ['Rjng']: 'Rejang',
  ['Rohg']: 'Hanifi Rohingya',
  ['Roro']: 'Rongorongo',
  ['Rumin']: 'Rumi numerals',
  ['Ruminumerals']: 'Rumi numerals',
  ['Runr']: 'Runic',
  ['Samr']: 'Samaritan',
  ['Sarb']: 'Old South Arabian',
  ['Saur']: 'Saurashtra',
  ['Semap']: 'flag semaphore',
  ['Sgnw']: 'SignWriting',
  ['Shaw']: 'Shavian',
  ['Shrd']: 'Sharada',
  ['Shui']: 'Sui',
  ['Sidd']: 'Siddham',
  ['Sind']: 'Khudawadi',
  ['Sinh']: 'Sinhalese',
  ['Sogd']: 'Sogdian',
  ['Sogo']: 'Old Sogdian',
  ['Sora']: 'Sorang Sompeng',
  ['Soyo']: 'Soyombo',
  ['Sund']: 'Sundanese',
  ['Sylo']: 'Syloti Nagri',
  ['Syrc']: 'Syriac',
  ['Tagb']: 'Tagbanwa',
  ['Takr']: 'Takri',
  ['Tale']: 'Tai Nüa',
  ['Talu']: 'New Tai Lue',
  ['Taml']: 'Tamil',
  ['Tang']: 'Tangut',
  ['Tavt']: 'Tai Viet',
  ['Telu']: 'Telugu',
  ['Teng']: 'Tengwar',
  ['Tfng']: 'Tifinagh',
  ['Tglg']: 'Baybayin',
  ['Thaa']: 'Thaana',
  ['Thai']: 'Thai',
  ['Tibt']: 'Tibetan',
  ['Tirh']: 'Tirhuta',
  ['Tnsa']: 'Tangsa',
  ['Toto']: 'Toto',
  ['Ugar']: 'Ugaritic',
  ['Vaii']: 'Vai',
  ['Visp']: 'Visible Speech',
  ['Vith']: 'Vithkuqi',
  ['Wara']: 'Varang Kshiti',
  ['Wcho']: 'Wancho',
  ['Wole']: 'Woleai',
  ['Xpeo']: 'Old Persian',
  ['Xsux']: 'Cuneiform',
  ['Yezi']: 'Yezidi',
  ['Yiii']: 'Yi',
  ['Zanb']: 'Zanabazar Square',
  ['Zmth']: 'mathematical notation',
  ['Zsym']: 'symbol',
  ['Zyyy']: 'undetermined',
  ['Zzzz']: 'uncoded',
  ['as-Beng']: 'Assamese',
  ['fa-Arab']: 'Arabic',
  ['kk-Arab']: 'Arabic',
  ['ks-Arab']: 'Arabic',
  ['ku-Arab']: 'Arabic',
  ['mnc-Mong']: 'Manchu',
  ['ms-Arab']: 'Arabic',
  ['musical']: 'Musical notation',
  ['mzn-Arab']: 'Arabic',
  ['ota-Arab']: 'Arabic',
  ['pa-Arab']: 'Shahmukhi',
  ['pal-Avst']: 'Pazend',
  ['pjt-Latn']: 'Latin',
  ['polytonic']: 'Greek',
  ['ps-Arab']: 'Arabic',
  ['sd-Arab']: 'Arabic',
  ['sit-tam-Tibt']: 'Tamyig',
  ['sjo-Mong']: 'Xibe',
  ['tt-Arab']: 'Arabic',
  ['ug-Arab']: 'Arabic',
  ['ur-Arab']: 'Arabic',
  ['xka-Arab']: 'Arabic',
  ['xwo-Mong']: 'Clear Script',
  ['xzh-Tibt']: 'Zhang-Zhung',
};
